### ISSUE TITLE
there is some DB issue

### ISSUE THREAD

**Issue by jhutar** [jhutar/jhutar-slack-bot#2]

**Comment by jhutar** [comment]
Looking into logs, I have found this:
```
ERROR:slack_bolt.App:Failed to run listener function (error: (sqlite3.IntegrityError) UNIQUE constraint failed: message.ts
[SQL: INSERT INTO message (ts, user, message, thread_ts) VALUES (?, ?, ?, ?)]
[parameters: (1656600238.255129, '...', 'Done:\n...', 1656592205.239559)]
(Background on this error at: https://sqlalche.me/e/14/gkpj))
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1820, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: message.ts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/slack_bolt/listener/thread_runner.py", line 124, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/usr/local/lib/python3.6/site-packages/slack_bolt/listener/custom_listener.py", line 56, in run_ack_function
    this_func=self.ack_function,
  File "./app.py", line 141, in message_hello
    context["db"].session.commit()
  File "<string>", line 2, in commit
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 3383, in flush
    self._flush(objects)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 3523, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 3483, in _flush
    flush_context.execute()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 633, in execute
    uow,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 250, in save_obj
    insert,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1098, in _emit_insert_statements
    statement, multiparams, execution_options=execution_options
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1508, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1863, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2044, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1820, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: message.ts
[SQL: INSERT INTO message (ts, user, message, thread_ts) VALUES (?, ?, ?, ?)]
[parameters: (1656600238.255129, '...', 'Done:\n...', 1656592205.239559)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by jhutar** [comment]
And this:
```
ERROR:slack_bolt.App:Failed to run listener function (error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: message.ts
[SQL: INSERT INTO message (ts, user, message, thread_ts) VALUES (?, ?, ?, ?)]
[parameters: (1656600238.255129, '...', 'Done:\n...', 1656592205.239559)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/slack_bolt/listener/thread_runner.py", line 124, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/usr/local/lib/python3.6/site-packages/slack_bolt/listener/custom_listener.py", line 56, in run_ack_function
    this_func=self.ack_function,
  File "./app.py", line 129, in message_hello
    parent_list = [i[0] for i in ThreadsToFollow.query.with_entities(ThreadsToFollow.thread_ts).all()]
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2768, in all
    return self._iter().all()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 2906, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1711, in execute
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 608, in _assert_active
    code="7s2a",
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: message.ts
[SQL: INSERT INTO message (ts, user, message, thread_ts) VALUES (?, ?, ?, ?)]
[parameters: (1656600238.255129, '...', 'Done:\n...', 1656592205.239559)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
```
